#!/usr/bin/env bash

# tunnel.sh
# Interactive SSH tunnel manager with optional auto-start on boot.

set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.env"
LOG_DIR="$SCRIPT_DIR/logs"
LOG_FILE="$LOG_DIR/tunnel.log"
CRON_MARKER="# tunnel_manager_auto"

# -----------------------------
# Logging helpers
# -----------------------------
log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp
    timestamp="$(date '+%Y-%m-%d %H:%M:%S')"
    echo "[$timestamp] [$level] $message" | tee -a "$LOG_FILE"
}

info() { log "INFO" "$*"; }
success() { log "SUCCESS" "$*"; }
error() { log "ERROR" "$*" >&2; }

# -----------------------------
# Utility checks/validators
# -----------------------------
ensure_log_dir() {
    mkdir -p "$LOG_DIR"
    touch "$LOG_FILE"
}

require_tool() {
    local tool="$1"
    if ! command -v "$tool" >/dev/null 2>&1; then
        error "Required tool '$tool' is not installed or not in PATH."
        return 1
    fi
}

is_valid_ip() {
    local ip="$1"
    local IFS='.'
    local -a octets

    # Basic IPv4 pattern check
    [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1

    read -r -a octets <<< "$ip"
    for octet in "${octets[@]}"; do
        ((octet >= 0 && octet <= 255)) || return 1
    done

    return 0
}

is_valid_port() {
    local port="$1"
    [[ "$port" =~ ^[0-9]+$ ]] || return 1
    ((port >= 1 && port <= 65535)) || return 1
    return 0
}

prompt_non_empty() {
    local prompt_text="$1"
    local value

    while true; do
        read -r -p "$prompt_text" value
        if [[ -n "$value" ]]; then
            echo "$value"
            return 0
        fi
        error "Input cannot be empty."
    done
}

get_script_path() {
    if command -v realpath >/dev/null 2>&1; then
        realpath "$0"
    elif command -v readlink >/dev/null 2>&1; then
        readlink -f "$0"
    else
        echo "$SCRIPT_DIR/tunnel.sh"
    fi
}

# -----------------------------
# Tunnel command assembly/start
# -----------------------------
build_forwarding_rules() {
    local -n _out_array="$1"
    local i

    _out_array=()
    for ((i = 0; i < PORT_COUNT; i++)); do
        _out_array+=("-L" "${LOCAL_PORTS[$i]}:127.0.0.1:${REMOTE_PORTS[$i]}")
    done
}

forwarded_ports_summary() {
    local i
    local summary=""

    for ((i = 0; i < PORT_COUNT; i++)); do
        summary+="${LOCAL_PORTS[$i]}->${REMOTE_PORTS[$i]}"
        if ((i < PORT_COUNT - 1)); then
            summary+=", "
        fi
    done

    echo "$summary"
}

start_tunnel() {
    local -a base_cmd
    local -a full_cmd
    local -a forwarding

    build_forwarding_rules forwarding

    base_cmd=(ssh -N -f -o ExitOnForwardFailure=yes)

    if [[ "$AUTH_METHOD" == "key" ]]; then
        if [[ ! -f "$KEY_PATH" ]]; then
            error "SSH key file not found: $KEY_PATH"
            return 1
        fi
        if [[ ! -r "$KEY_PATH" ]]; then
            error "SSH key file is not readable: $KEY_PATH"
            return 1
        fi
        full_cmd=("${base_cmd[@]}" -i "$KEY_PATH" "${forwarding[@]}" "${SSH_USER}@${SERVER_IP}")
    else
        require_tool sshpass || return 1
        full_cmd=(sshpass -p "$PASSWORD" "${base_cmd[@]}" "${forwarding[@]}" "${SSH_USER}@${SERVER_IP}")
    fi

    info "Starting SSH tunnel to $SSH_USER@$SERVER_IP"
    if "${full_cmd[@]}" >> "$LOG_FILE" 2>&1; then
        success "Tunnel started successfully. Forwarded ports: $(forwarded_ports_summary)"
        return 0
    else
        error "Failed to start SSH tunnel. Check $LOG_FILE for details."
        return 1
    fi
}

# -----------------------------
# Config persistence/load
# -----------------------------
save_config() {
    local old_umask
    old_umask="$(umask)"
    umask 077

    {
        echo "# Auto-generated by tunnel.sh"
        printf 'SSH_USER=%q\n' "$SSH_USER"
        printf 'SERVER_IP=%q\n' "$SERVER_IP"
        printf 'AUTH_METHOD=%q\n' "$AUTH_METHOD"
        printf 'KEY_PATH=%q\n' "${KEY_PATH:-}"
        printf 'PASSWORD=%q\n' "${PASSWORD:-}"
        printf 'PORT_COUNT=%q\n' "$PORT_COUNT"

        local i
        for ((i = 0; i < PORT_COUNT; i++)); do
            printf 'LOCAL_PORT_%d=%q\n' "$((i + 1))" "${LOCAL_PORTS[$i]}"
            printf 'REMOTE_PORT_%d=%q\n' "$((i + 1))" "${REMOTE_PORTS[$i]}"
        done
    } > "$CONFIG_FILE"

    chmod 600 "$CONFIG_FILE"
    umask "$old_umask"

    success "Configuration saved to $CONFIG_FILE"
}

load_config() {
    if [[ ! -f "$CONFIG_FILE" ]]; then
        error "Config file not found: $CONFIG_FILE"
        return 1
    fi

    # shellcheck source=/dev/null
    source "$CONFIG_FILE"

    if [[ -z "${SSH_USER:-}" || -z "${SERVER_IP:-}" || -z "${AUTH_METHOD:-}" || -z "${PORT_COUNT:-}" ]]; then
        error "Config file is missing required fields."
        return 1
    fi

    if [[ "$AUTH_METHOD" != "password" && "$AUTH_METHOD" != "key" ]]; then
        error "Invalid AUTH_METHOD in config. Expected 'password' or 'key'."
        return 1
    fi

    if ! [[ "$PORT_COUNT" =~ ^[0-9]+$ ]] || ((PORT_COUNT < 1)); then
        error "Invalid PORT_COUNT in config."
        return 1
    fi

    LOCAL_PORTS=()
    REMOTE_PORTS=()

    local i
    for ((i = 1; i <= PORT_COUNT; i++)); do
        local lp_var="LOCAL_PORT_$i"
        local rp_var="REMOTE_PORT_$i"
        local lp="${!lp_var:-}"
        local rp="${!rp_var:-}"

        if ! is_valid_port "$lp" || ! is_valid_port "$rp"; then
            error "Invalid port mapping in config for entry #$i."
            return 1
        fi

        LOCAL_PORTS+=("$lp")
        REMOTE_PORTS+=("$rp")
    done

    if [[ "$AUTH_METHOD" == "key" ]]; then
        if [[ -z "${KEY_PATH:-}" ]]; then
            error "KEY_PATH is missing in config for key authentication."
            return 1
        fi
    else
        if [[ -z "${PASSWORD:-}" ]]; then
            error "PASSWORD is missing in config for password authentication."
            return 1
        fi
    fi

    return 0
}

# -----------------------------
# Cron setup for auto-start
# -----------------------------
setup_reboot_cron() {
    require_tool crontab || return 1

    local script_path
    script_path="$(get_script_path)"

    local cron_line
    cron_line="@reboot /bin/bash \"$script_path\" --auto >> \"$LOG_DIR/auto-start.log\" 2>&1 $CRON_MARKER"

    local existing
    existing="$(crontab -l 2>/dev/null || true)"

    if echo "$existing" | grep -Fq "$CRON_MARKER"; then
        info "Auto-start cron job already exists. Skipping duplicate entry."
        return 0
    fi

    if { printf '%s\n' "$existing"; printf '%s\n' "$cron_line"; } | crontab -; then
        success "Auto-start cron job added. Tunnel will start on reboot."
        return 0
    else
        error "Failed to add cron job."
        return 1
    fi
}

# -----------------------------
# Interactive input flow
# -----------------------------
collect_interactive_config() {
    SSH_USER="$(prompt_non_empty 'Enter SSH username: ')"

    while true; do
        SERVER_IP="$(prompt_non_empty 'Enter remote server IP address: ')"
        if is_valid_ip "$SERVER_IP"; then
            break
        fi
        error "Invalid IP address format. Please enter a valid IPv4 address."
    done

    while true; do
        echo "Select authentication method:"
        echo "  1) Password"
        echo "  2) SSH key file"
        read -r -p "Choice (1 or 2): " auth_choice

        case "$auth_choice" in
            1)
                AUTH_METHOD="password"
                read -r -s -p "Enter SSH password: " PASSWORD
                echo
                if [[ -z "$PASSWORD" ]]; then
                    error "Password cannot be empty."
                else
                    KEY_PATH=""
                    break
                fi
                ;;
            2)
                AUTH_METHOD="key"
                PASSWORD=""
                while true; do
                    KEY_PATH="$(prompt_non_empty 'Enter full path to private key file: ')"
                    if [[ -f "$KEY_PATH" && -r "$KEY_PATH" ]]; then
                        break
                    fi
                    error "Key file does not exist or is not readable."
                done
                break
                ;;
            *)
                error "Invalid selection. Please choose 1 or 2."
                ;;
        esac
    done

    while true; do
        read -r -p "How many ports do you want to forward? " PORT_COUNT
        if [[ "$PORT_COUNT" =~ ^[0-9]+$ ]] && ((PORT_COUNT > 0)); then
            break
        fi
        error "Please enter a valid positive number."
    done

    LOCAL_PORTS=()
    REMOTE_PORTS=()

    local i lp rp
    for ((i = 1; i <= PORT_COUNT; i++)); do
        while true; do
            read -r -p "Port mapping #$i - Local port: " lp
            if is_valid_port "$lp"; then
                break
            fi
            error "Invalid local port. Must be numeric between 1 and 65535."
        done

        while true; do
            read -r -p "Port mapping #$i - Remote port: " rp
            if is_valid_port "$rp"; then
                break
            fi
            error "Invalid remote port. Must be numeric between 1 and 65535."
        done

        LOCAL_PORTS+=("$lp")
        REMOTE_PORTS+=("$rp")
    done
}

handle_autostart_prompt() {
    local answer
    while true; do
        read -r -p "Do you want the tunnel to auto-start on system boot? (y/n): " answer
        case "${answer,,}" in
            y|yes)
                save_config || return 1
                setup_reboot_cron || return 1
                return 0
                ;;
            n|no)
                info "Auto-start not enabled."
                return 0
                ;;
            *)
                error "Please answer y or n."
                ;;
        esac
    done
}

# -----------------------------
# Modes
# -----------------------------
run_interactive_mode() {
    require_tool ssh || return 1

    collect_interactive_config

    if start_tunnel; then
        handle_autostart_prompt || return 1
    else
        return 1
    fi
}

run_auto_mode() {
    require_tool ssh || return 1

    info "Running in --auto mode. Loading configuration..."
    load_config || return 1

    if [[ "$AUTH_METHOD" == "password" ]]; then
        require_tool sshpass || return 1
    fi

    start_tunnel
}

show_usage() {
    echo "Usage: $0 [--auto]"
    echo "  --auto   Start tunnel from config.env without interactive prompts"
}

main() {
    ensure_log_dir

    case "${1:-}" in
        --auto)
            run_auto_mode || exit 1
            ;;
        "")
            run_interactive_mode || exit 1
            ;;
        -h|--help)
            show_usage
            ;;
        *)
            error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
}

main "$@"
